# Generated by Django 4.1.6 on 2023-05-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_flutter', '0004_remove_user_groups_alter_group_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_joined',
            field=models.ManyToManyField(to='api_flutter.group'),
        ),
    ]
