# Generated by Django 4.1.6 on 2023-05-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_flutter', '0011_alter_point_group_alter_point_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point', to='api_flutter.group'),
        ),
        migrations.AlterField(
            model_name='point',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point', to='api_flutter.person'),
        ),
    ]
