# Generated by Django 4.1.6 on 2023-05-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_flutter', '0014_person_last_action_joinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='last_action',
        ),
    ]
