# Generated by Django 4.1.6 on 2023-05-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_flutter', '0005_user_group_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group_joined',
            new_name='user_joined',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_flutter.user'),
        ),
    ]
