# Generated by Django 4.1.6 on 2023-05-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_flutter', '0006_rename_group_joined_user_user_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_joined',
            new_name='group_joined',
        ),
    ]
