# Generated by Django 4.1.6 on 2023-05-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_flutter', '0007_rename_user_joined_user_group_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group_joined',
        ),
        migrations.AddField(
            model_name='group',
            name='user_joined',
            field=models.ManyToManyField(blank=True, related_name='joined_groups', to='api_flutter.user'),
        ),
    ]
