# Generated by Django 4.1.6 on 2023-05-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_flutter', '0009_rename_user_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='point',
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_flutter.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_flutter.person')),
            ],
        ),
    ]
