# Generated by Django 4.1.6 on 2023-05-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_flutter', '0010_remove_person_point_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point', to='api_flutter.group'),
        ),
        migrations.AlterField(
            model_name='point',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point', to='api_flutter.person'),
        ),
    ]
