# Generated by Django 4.1.6 on 2023-05-14 12:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_flutter', '0013_alter_point_group_alter_point_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_action',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_request', to='api_flutter.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_request', to='api_flutter.person')),
            ],
            options={
                'unique_together': {('person', 'group')},
            },
        ),
    ]
