# Generated by Django 4.2.1 on 2023-05-17 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_flutter', '0015_remove_person_last_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_groups', to='api_flutter.person'),
        ),
    ]
